In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import files
rawdata = files.upload()

Saving poc1insurance dataset.csv to poc1insurance dataset.csv


In [ ]:
df=pd.read_csv('poc1insurance dataset.csv')
df

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [ ]:
df.shape

(1338, 7)

In [ ]:
df.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [ ]:
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
df.tail()

age     sex    bmi  children smoker     region     charges
1333   50    male  30.97         3     no  northwest  10600.5483
1334   18  female  31.92         0     no  northeast   2205.9808
1335   18  female  36.85         0     no  southeast   1629.8335
1336   21  female  25.80         0     no  southwest   2007.9450
1337   61  female  29.07         0    yes  northwest  29141.3603

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [ ]:
df.describe()

age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [ ]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [ ]:
X=df.iloc[:,[0,1,2,3,4,5]]
X

age     sex     bmi  children smoker     region
0      19  female  27.900         0    yes  southwest
1      18    male  33.770         1     no  southeast
2      28    male  33.000         3     no  southeast
3      33    male  22.705         0     no  northwest
4      32    male  28.880         0     no  northwest
...   ...     ...     ...       ...    ...        ...
1333   50    male  30.970         3     no  northwest
1334   18  female  31.920         0     no  northeast
1335   18  female  36.850         0     no  southeast
1336   21  female  25.800         0     no  southwest
1337   61  female  29.070         0    yes  northwest

[1338 rows x 6 columns]

In [ ]:
feature_name_indexing=df[['age', 'sex', 'bmi', 'children', 'region']]
feature_name_indexing

age     sex     bmi  children     region
0      19  female  27.900         0  southwest
1      18    male  33.770         1  southeast
2      28    male  33.000         3  southeast
3      33    male  22.705         0  northwest
4      32    male  28.880         0  northwest
...   ...     ...     ...       ...        ...
1333   50    male  30.970         3  northwest
1334   18  female  31.920         0  northeast
1335   18  female  36.850         0  southeast
1336   21  female  25.800         0  southwest
1337   61  female  29.070         0  northwest

[1338 rows x 5 columns]

In [ ]:
Use_age_as_index=pd.read_csv('poc1insurance dataset.csv',index_col="age")
Use_age_as_index

sex     bmi  children smoker     region      charges
age                                                         
19   female  27.900         0    yes  southwest  16884.92400
18     male  33.770         1     no  southeast   1725.55230
28     male  33.000         3     no  southeast   4449.46200
33     male  22.705         0     no  northwest  21984.47061
32     male  28.880         0     no  northwest   3866.85520
..      ...     ...       ...    ...        ...          ...
50     male  30.970         3     no  northwest  10600.54830
18   female  31.920         0     no  northeast   2205.98080
18   female  36.850         0     no  southeast   1629.83350
21   female  25.800         0     no  southwest   2007.94500
61   female  29.070         0    yes  northwest  29141.36030

[1338 rows x 6 columns]

In [ ]:
Y=df.iloc[:,[-1]]
Y

charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [ ]:
sex=X['sex'].unique()
sex

array(['female', 'male'], dtype=object)

In [ ]:
smoker=X['smoker'].unique()
smoker

array(['yes', 'no'], dtype=object)

In [ ]:
region_uniqe=X['region'].unique()
region_uniqe

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [ ]:
sex_enc=pd.get_dummies(X['sex'])
sex_enc

female  male
0          1     0
1          0     1
2          0     1
3          0     1
4          0     1
...      ...   ...
1333       0     1
1334       1     0
1335       1     0
1336       1     0
1337       1     0

[1338 rows x 2 columns]

In [ ]:
X

age     sex     bmi  children smoker     region
0      19  female  27.900         0    yes  southwest
1      18    male  33.770         1     no  southeast
2      28    male  33.000         3     no  southeast
3      33    male  22.705         0     no  northwest
4      32    male  28.880         0     no  northwest
...   ...     ...     ...       ...    ...        ...
1333   50    male  30.970         3     no  northwest
1334   18  female  31.920         0     no  northeast
1335   18  female  36.850         0     no  southeast
1336   21  female  25.800         0     no  southwest
1337   61  female  29.070         0    yes  northwest

[1338 rows x 6 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [ ]:
region=X.iloc[:,[-1]]
region

region
0     southwest
1     southeast
2     southeast
3     northwest
4     northwest
...         ...
1333  northwest
1334  northeast
1335  southeast
1336  southwest
1337  northwest

[1338 rows x 1 columns]

In [ ]:
region_encoded=le.fit_transform(region)
region_encoded

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([3, 2, 2, ..., 2, 3, 1])

In [ ]:
X['region']=le.fit_transform(X['region'])
X

<ipython-input-30-62fd67e309fc>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['region']=le.fit_transform(X['region'])


age     sex     bmi  children smoker  region
0      19  female  27.900         0    yes       3
1      18    male  33.770         1     no       2
2      28    male  33.000         3     no       2
3      33    male  22.705         0     no       1
4      32    male  28.880         0     no       1
...   ...     ...     ...       ...    ...     ...
1333   50    male  30.970         3     no       1
1334   18  female  31.920         0     no       0
1335   18  female  36.850         0     no       2
1336   21  female  25.800         0     no       3
1337   61  female  29.070         0    yes       1

[1338 rows x 6 columns]

In [ ]:
X1=pd.get_dummies(X)
X1

age     bmi  children  region  sex_female  sex_male  smoker_no  \
0      19  27.900         0       3           1         0          0   
1      18  33.770         1       2           0         1          1   
2      28  33.000         3       2           0         1          1   
3      33  22.705         0       1           0         1          1   
4      32  28.880         0       1           0         1          1   
...   ...     ...       ...     ...         ...       ...        ...   
1333   50  30.970         3       1           0         1          1   
1334   18  31.920         0       0           1         0          1   
1335   18  36.850         0       2           1         0          1   
1336   21  25.800         0       3           1         0          1   
1337   61  29.070         0       1           1         0          0   

      smoker_yes  
0              1  
1              0  
2              0  
3              0  
4              0  
...          ...  
1333           0  
1334           0  
1335           0  
1336           0  
1337           1  

[1338 rows x 8 columns]

In [ ]:
from sklearn.preprocessing import Normalizer

In [ ]:
X2=Normalizer(norm='l1').fit_transform(X1)
X2

array([[0.36608863, 0.53757225, 0.        , ..., 0.        , 0.        ,
        0.01926782],
       [0.31706887, 0.59485644, 0.01761494, ..., 0.01761494, 0.01761494,
        0.        ],
       [0.41176471, 0.48529412, 0.04411765, ..., 0.01470588, 0.01470588,
        0.        ],
       ...,
       [0.30586236, 0.62616822, 0.        , ..., 0.        , 0.01699235,
        0.        ],
       [0.40540541, 0.4980695 , 0.        , ..., 0.        , 0.01930502,
        0.        ],
       [0.65542065, 0.31234555, 0.        , ..., 0.        , 0.        ,
        0.0107446 ]])

In [ ]:
X_norm2=Normalizer(norm='l2').fit_transform(X1)
X_norm2

array([[0.56017958, 0.82257949, 0.        , ..., 0.        , 0.        ,
        0.02948314],
       [0.46925102, 0.88036705, 0.0260695 , ..., 0.0260695 , 0.0260695 ,
        0.        ],
       [0.64440223, 0.75947406, 0.0690431 , ..., 0.02301437, 0.02301437,
        0.        ],
       ...,
       [0.4381232 , 0.89693556, 0.        , ..., 0.        , 0.02434018,
        0.        ],
       [0.62815718, 0.77173596, 0.        , ..., 0.        , 0.02991225,
        0.        ],
       [0.9024355 , 0.4300623 , 0.        , ..., 0.        , 0.        ,
        0.01479402]])

In [ ]:
from sklearn import preprocessing
X_normal_normalize=preprocessing.normalize(X1)
X_normal_normalize

array([[0.56017958, 0.82257949, 0.        , ..., 0.        , 0.        ,
        0.02948314],
       [0.46925102, 0.88036705, 0.0260695 , ..., 0.0260695 , 0.0260695 ,
        0.        ],
       [0.64440223, 0.75947406, 0.0690431 , ..., 0.02301437, 0.02301437,
        0.        ],
       ...,
       [0.4381232 , 0.89693556, 0.        , ..., 0.        , 0.02434018,
        0.        ],
       [0.62815718, 0.77173596, 0.        , ..., 0.        , 0.02991225,
        0.        ],
       [0.9024355 , 0.4300623 , 0.        , ..., 0.        , 0.        ,
        0.01479402]])

In [ ]:
from sklearn.preprocessing import StandardScaler
std=StandardScaler()
X1_std=std.fit_transform(X1)
X1_std

array([[-1.43876426, -0.45332   , -0.90861367, ..., -1.0105187 ,
        -1.97058663,  1.97058663],
       [-1.50996545,  0.5096211 , -0.07876719, ...,  0.98959079,
         0.5074631 , -0.5074631 ],
       [-0.79795355,  0.38330685,  1.58092576, ...,  0.98959079,
         0.5074631 , -0.5074631 ],
       ...,
       [-1.50996545,  1.0148781 , -0.90861367, ..., -1.0105187 ,
         0.5074631 , -0.5074631 ],
       [-1.29636188, -0.79781341, -0.90861367, ..., -1.0105187 ,
         0.5074631 , -0.5074631 ],
       [ 1.55168573, -0.26138796, -0.90861367, ..., -1.0105187 ,
        -1.97058663,  1.97058663]])

In [ ]:
X1_scale=preprocessing.scale(X1)
X1_scale

array([[-1.43876426, -0.45332   , -0.90861367, ..., -1.0105187 ,
        -1.97058663,  1.97058663],
       [-1.50996545,  0.5096211 , -0.07876719, ...,  0.98959079,
         0.5074631 , -0.5074631 ],
       [-0.79795355,  0.38330685,  1.58092576, ...,  0.98959079,
         0.5074631 , -0.5074631 ],
       ...,
       [-1.50996545,  1.0148781 , -0.90861367, ..., -1.0105187 ,
         0.5074631 , -0.5074631 ],
       [-1.29636188, -0.79781341, -0.90861367, ..., -1.0105187 ,
         0.5074631 , -0.5074631 ],
       [ 1.55168573, -0.26138796, -0.90861367, ..., -1.0105187 ,
        -1.97058663,  1.97058663]])

In [ ]:
x

array([[0.36608863, 0.53757225, 0.        , ..., 0.        , 0.        ,
        0.01926782],
       [0.31706887, 0.59485644, 0.01761494, ..., 0.01761494, 0.01761494,
        0.        ],
       [0.41176471, 0.48529412, 0.04411765, ..., 0.01470588, 0.01470588,
        0.        ],
       ...,
       [0.30586236, 0.62616822, 0.        , ..., 0.        , 0.01699235,
        0.        ],
       [0.40540541, 0.4980695 , 0.        , ..., 0.        , 0.01930502,
        0.        ],
       [0.65542065, 0.31234555, 0.        , ..., 0.        , 0.        ,
        0.0107446 ]])

In [ ]:
X2

array([[0.36608863, 0.53757225, 0.        , ..., 0.        , 0.        ,
        0.01926782],
       [0.31706887, 0.59485644, 0.01761494, ..., 0.01761494, 0.01761494,
        0.        ],
       [0.41176471, 0.48529412, 0.04411765, ..., 0.01470588, 0.01470588,
        0.        ],
       ...,
       [0.30586236, 0.62616822, 0.        , ..., 0.        , 0.01699235,
        0.        ],
       [0.40540541, 0.4980695 , 0.        , ..., 0.        , 0.01930502,
        0.        ],
       [0.65542065, 0.31234555, 0.        , ..., 0.        , 0.        ,
        0.0107446 ]])

In [ ]:
Y

charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split (X2, Y, test_size = 0.2, random_state = 1234)  # 80:20 , 70:30, # parado principle
x_train, x_test, y_train, y_test

(array([[0.69747167, 0.25893636, 0.        , ..., 0.01089799, 0.        ,
         0.01089799],
        [0.41383388, 0.50734062, 0.03941275, ..., 0.01970638, 0.01970638,
         0.        ],
        [0.47832125, 0.45995988, 0.        , ..., 0.01542972, 0.        ,
         0.01542972],
        ...,
        [0.43365134, 0.49200843, 0.04956015, ..., 0.01239004, 0.01239004,
         0.        ],
        [0.31986532, 0.5959596 , 0.        , ..., 0.01683502, 0.01683502,
         0.        ],
        [0.36062027, 0.56725568, 0.        , ..., 0.        , 0.01803101,
         0.        ]]),
 array([[0.66807058, 0.2883596 , 0.        , ..., 0.01452327, 0.01452327,
         0.        ],
        [0.46433878, 0.47994056, 0.01857355, ..., 0.01857355, 0.01857355,
         0.        ],
        [0.47385621, 0.44444444, 0.        , ..., 0.01633987, 0.01633987,
         0.        ],
        ...,
        [0.58957779, 0.37238494, 0.        , ..., 0.        , 0.00950932,
         0.        ],
        [0.6

In [ ]:
from sklearn.linear_model import LinearRegression
std_reg = LinearRegression()  # y = mx+c
std_reg.fit(x_train, y_train)

LinearRegression()

In [ ]:
y_predict = std_reg.predict(x_test)
y_predict

array([[ 7584.],
       [ 2848.],
       [ 4400.],
       [10560.],
       [15584.],
       [14512.],
       [29024.],
       [ 4128.],
       [30656.],
       [ 5968.],
       [12240.],
       [12448.],
       [14704.],
       [14288.],
       [30624.],
       [ 8176.],
       [ 8384.],
       [13936.],
       [11072.],
       [ 6464.],
       [ 6848.],
       [-1600.],
       [12800.],
       [12784.],
       [30560.],
       [12608.],
       [ 2976.],
       [29920.],
       [ 4944.],
       [14544.],
       [-4160.],
       [13632.],
       [ 7200.],
       [15744.],
       [ 7984.],
       [12336.],
       [ 8128.],
       [ 9280.],
       [15520.],
       [ 3504.],
       [11040.],
       [  848.],
       [ 8640.],
       [13920.],
       [10496.],
       [15008.],
       [ 5696.],
       [28976.],
       [30848.],
       [30208.],
       [-6992.],
       [15744.],
       [10288.],
       [12512.],
       [10480.],
       [11776.],
       [11984.],
       [ 9792.],
       [15392.

In [ ]:
y_test

charges
395    7526.70645
809    3309.79260
324    2866.09100
237    4463.20510
1132  20709.02034
...           ...
923    4320.41085
169    4827.90495
928   13470.80440
1084  15019.76005
1316   1731.67700

[268 rows x 1 columns]

In [ ]:
Y

charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]